version: '3'

services:
  web:
    volumes:
    - static-volume:/home/flask/app/web/project/static
    command: /usr/local/bin/gunicorn -w 2 -b :8000 project:app


  postgres:
    volumes:
      - data-volume:/var/lib/postgresql/data


volumes:
  data-volume:
  static-volume:


# docker-compose build
# docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d